### ISSUE TITLE
"unexpected character 'p' while parsing major version" for "language_version: python3"

### ISSUE THREAD

**Issue by hugovk** [j178/prefligit#227]
Using the latest commit on macOS:

```console
❯ prefligit --version
prefligit 0.0.10 (2216474ce 2025-03-27)
```

With this config:
```yaml
❯ cat .pre-commit-config.yaml
repos:
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.5.0
    hooks:
      - id: tox-ini-fmt
```

Gives:

```console
❯ prefligit run --all-files
error: Failed to parse `/Users/hugo/.cache/prefligit/repos/54a9fcd80b2c4079/.pre-commit-hooks.yaml`
  caused by: .[0]: invalid version requirement: unexpected character 'p' while parsing major version number at line 1 column 3
```

That file contains:

```yaml
❯ cat /Users/hugo/.cache/prefligit/repos/54a9fcd80b2c4079/.pre-commit-hooks.yaml
- id: tox-ini-fmt
  name: tox-ini-fmt
  description: apply a consistent format to `tox.ini` files
  entry: tox-ini-fmt
  language: python
  language_version: python3
  files: '(^|/)tox\.ini$'
```

If I remove `language_version: python3` it works:

```console
❯ prefligit run --all-files
tox-ini-fmt..............................................................Passed
```

Docs: https://pre-commit.com/#overriding-language-version
